import Footer from "@/widjets/Footer";
import Header from "@/widjets/Header";
import Head from "next/head";
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <title>Tourist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
       <section className="back">
          <Header/>
        <div className="container">

          <div className="banner">
            <div className="left_banner">
              <p className="txt_4">Follow us</p>

             <Link href="#">
              <div className="icon">
                <img src="./img/icn.png" alt="icon" />
              </div>
             </Link>

              <Link href="#">
              <div className="icon">
                <img src="./img/icn_2.png" alt="icon" />
              </div>
              </Link>
            </div>

            <div className="banner_elm">
              <div className="banner_top">
                <div className="line_top"></div>
                <p className="txt_1">A Hiking guide</p>
              </div>
                
                <h1 className="txt_2">
                 Be prepared for the <br />
                Mountains and beyond!
                </h1>

                <div className="banner_bottom">
                  <Link href="#" className="txt_3">scroll down</Link>
                  <Link href="#" className="arrow">↓</Link>
                </div>
            </div>

            <div className="left_rigth">
                <div className="lf">
                  <p className="txt_5">Start</p>
                  <p className="txt_5">01</p>
                  <p className="txt_5">02</p>
                  <p className="txt_5">03</p>
                </div>

               <div className="left_r">
                <div className="ln_t"></div>
               </div>
            </div>
          </div>
        </div>
       </section>

        <section className="bb">
          <div className="container">
            <div className="lvl_block">
               <div className="lvl_item">
                  <p className="txt_6">01</p>
                  <div className="left_lvl">
                  <div className="lvl_top">
                    <div className="line_lv"></div>
                    <p className="txt_7">GEt Started</p>
                  </div>

                  <p className="txt_8">
                    What level of  hiker  <br />
                     are you?
                  </p>
                    
                    <p className="txt_9">
                      Determining what level of hiker you are can be an important tool when  <br />
                      planning future hikes. This hiking level guide will help you plan hikes  <br />
                      according to different hike ratings set by various websites like All Trails and  <br />
                      Modern Hiker. What type of hiker are you – novice, moderate, advanced  <br />
                      moderate, expert, or expert backpacker? 
                    </p>

                    <div className="read_bi">
                       <Link href="#" className="lnk_4">
                       read more
                       </Link>

                       <Link href="#" className="arrw_lnk">
                        →
                       </Link>
                    </div>
                  </div>
                    
                  <div className="lvl_rigth">
                    <img src="./img/01.png" alt="" />
                  </div>
               </div>
                
                <div className="lvl_item">
                  <p className="txt_10">02</p>
                  <div className="lvl_rigth">
                    <img src="./img/02.png" alt="" />
                  </div>

                  <div className="left_lvl">
                  <div className="lvl_top">
                    <div className="line_lv"></div>
                    <p className="txt_7">Hiking Essentials</p>
                  </div>

                  <p className="txt_8">
                    Picking the right  <br />
                    Hiking Gear!
                  </p>
                    
                    <p className="txt_9">
                      The nice thing about beginning hiking is that you don’t really need any  <br />
                      special gear, you can probably get away with things you already have. <br />
                      Let’s start with clothing. A typical mistake hiking beginners make is wearing  <br />
                      jeans and regular clothes, which will get heavy and chafe wif they get  <br />
                      sweaty or wet.
                    </p>

                    <div className="read_bi">
                       <Link href="#" className="lnk_4">
                       read more
                       </Link>

                       <Link href="#" className="arrw_lnk">
                        →
                       </Link>
                    </div>
                  </div>
               </div>
                
                 <div className="lvl_item">
                  <p className="txt_6">03</p>
                  <div className="left_lvl">
                  <div className="lvl_top">
                    <div className="line_lv"></div>
                    <p className="txt_7">GEt Started</p>
                  </div>

                  <p className="txt_8">
                  Understand Your  <br />
                  Map & Timing
                  </p>
                    
                    <p className="txt_9">
                      To start, print out the hiking guide and map. If it’s raining, throw them in a  <br />
                      Zip-Lock bag. Read over the guide, study the map, and have a good idea <br />
                      of what to expect. I like to know what my next landmark is as I hike. For <br />
                      example, I’ll read the guide and know that say, in a mile, I make a right turn <br />
                      at the junction..
                    </p>

                    <div className="read_bi">
                       <Link href="#" className="lnk_4">
                       read more
                       </Link>

                       <Link href="#" className="arrw_lnk">
                        →
                       </Link>
                    </div>
                  </div>
                    
                  <div className="lvl_rigth">
                    <img src="./img/03.png" alt="" />
                  </div>
               </div>

            </div>
          </div>
        </section>

        <section className="footer_back">
          <div className="container">
            <Footer/>
          </div>
        </section>
        </main>
      </div>
    </>
  );
}
